### ISSUE TITLE
It doesn\'t seem possible to specify mobile App Store URLs other than for tiqr

### ISSUE THREAD

**Issue by phavekes** [OpenConext/Stepup-Project#228]
[This issue is imported from pivotal - Originaly created at Nov 29, 2017 by Joost van Dijk](https://www.pivotaltracker.com/story/show/153258493)

See for instance https://github.com/OpenConext/Stepup-SelfService/blob/develop/src/Surfnet/StepupSelfService/SelfServiceBundle/Controller/RegistrationController.php#L76
and
https://github.com/OpenConext/Stepup-SelfService/blob/develop/src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/views/Registration/partial/genericSecondFactor.html.twig#L19

This seems to be hardcoded to tiqr

**Comment by phavekes** [comment]
[Pull request](https://github.com/OpenConext/Stepup-SelfService/pull/130)

**Installation notes:**

1: Remove from parameters.yml
```yaml
tiqr_app_android_url: https://url-play-store
tiqr_app_ios_url: https://url-itunes
```

2: Set the Android and/or iOS URL in `samlstepupprovidres.yml` like this:

```yaml
surfnet_stepup_self_service_saml_stepup_provider:
    routes:
	...
    providers:
        tiqr:
            hosted:
                ...
            remote:
                ...
            view_config:
                ...
                description: %gssp_tiqr_description%                
                app_android_url: %gssp_tiqr_app_android_url%
                app_ios_url: %gssp_tiqr_app_ios_url%
		...
```

Note that the app url\'s are optional config settings. You could set up a provider with only an Android app url.

3: Update parameters
When adding one of the two supported app url\'s the description must be set accordingly. The `samlstepupproviders_parameters.yml` file for the explanation above:

```yaml
gssp_tiqr_description:
parameters:
    gssp_tiqr_description:
        en_GB: \'Log in with a smartphone app. For all smartphones with %%ios_link_start%%Apple iOS%%ios_link_end%% or %%android_link_start%%Android%%android_link_end%%.\'
        nl_NL: \'Log in met een app op je smartphone. Geschikt voor smartphones met %%ios_link_start%%Apple iOS%%ios_link_end%% of %%android_link_start%%Android%%android_link_end%%.\'    
```

The application wil validate the descriptions for the correct app url tokens.

PS: This was also [added to the Stepup-Deploy gssp configuration readme](https://github.com/OpenConext/Stepup-Deploy/blob/dev/docs/add-gssf-to-stepup.md). (Michiel Kodde - Dec 12, 2017)
